# Generated by Django 5.2.1 on 2025-06-01 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vocabularyitem',
            constraint=models.UniqueConstraint(fields=('user', 'word'), name='unique_user_word'),
        ),
    ]
