# Generated by Django 5.2.1 on 2025-06-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_vocabularyitem_unique_user_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('current_index', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='repeat_threshold',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
