# Generated by Django 5.2.1 on 2025-06-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0003_learningsession_telegramuser_repeat_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='days_before_review',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='enable_review_old_words',
            field=models.BooleanField(default=True),
        ),
    ]
