# Generated by Django 5.2.1 on 2025-06-01 18:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0004_telegramuser_days_before_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='consecutive_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='joined_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 6, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_reminder_sent_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_study_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='reminder_interval_days',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='total_study_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='repeat_threshold',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
