# Generated by Django 5.2.1 on 2025-06-01 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0005_telegramuser_consecutive_days_telegramuser_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='reminder_time',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
    ]
