# Generated by Django 5.2.1 on 2025-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0007_achievement'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vocabularyitem',
            name='unique_user_word',
        ),
        migrations.AddField(
            model_name='vocabularyitem',
            name='normalized_word',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddConstraint(
            model_name='vocabularyitem',
            constraint=models.UniqueConstraint(fields=('user', 'normalized_word'), name='unique_user_normalized_word'),
        ),
    ]
