# Generated by Django 5.2.1 on 2025-06-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0008_remove_vocabularyitem_unique_user_word_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocabularyitem',
            name='normalized_word',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
