# Generated by Django 5.2.1 on 2025-06-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0009_alter_vocabularyitem_normalized_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='part_of_speech',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
