# Generated by Django 5.2.3 on 2025-06-16 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0010_vocabularyitem_part_of_speech"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="irregular_correct",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
