# Generated by Django 5.2.3 on 2025-06-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0011_telegramuser_irregular_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="vocabularyitem",
            name="example_translation",
            field=models.TextField(blank=True, default=""),
        ),
    ]
