# Generated by Django 5.2 on 2025-06-17 00:00
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0012_vocabularyitem_example_translation"),
    ]

    operations = [
        migrations.CreateModel(
            name="IrregularVerbProgress",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("verb_base", models.CharField(max_length=50)),
                ("correct_count", models.PositiveIntegerField(default=0)),
                ("is_learned", models.BooleanField(default=False)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="vocab.telegramuser")),
            ],
            options={
                "unique_together": {("user", "verb_base")},
            },
        ),
    ]
