# Generated by Django 5.2.8 on 2026-03-07 13:01

import vocab.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0018_telegramuser_exercise_counters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weblogintoken',
            name='token',
            field=models.CharField(default=vocab.models.generate_web_login_token, max_length=64, unique=True),
        ),
    ]
