# Generated by Django 5.2.8 on 2026-03-07 13:06

from django.db import migrations, models


def backfill_learned_at(apps, schema_editor):
    VocabularyItem = apps.get_model("vocab", "VocabularyItem")
    VocabularyItem.objects.filter(is_learned=True, learned_at__isnull=True).update(learned_at=models.F("updated_at"))


def clear_backfill(apps, schema_editor):
    VocabularyItem = apps.get_model("vocab", "VocabularyItem")
    VocabularyItem.objects.update(learned_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0019_alter_weblogintoken_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabularyitem',
            name='learned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_learned_at, clear_backfill),
    ]
