# Generated by Django 5.2.8 on 2026-03-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0025_packpreparedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='auth_provider',
            field=models.CharField(default='telegram', max_length=20),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='password_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
