# Generated by Django 5.2.8 on 2026-04-17 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0038_packpreparedword_failure_backoff"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDailyEntitlementUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("usage_date", models.DateField()),
                ("new_items_added", models.PositiveIntegerField(default=0)),
                ("extra_image_regenerations", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vocab.telegramuser",
                    ),
                ),
            ],
            options={
                "ordering": ["-usage_date", "-id"],
                "unique_together": {("user", "usage_date")},
            },
        ),
    ]
