# Generated by Django 5.2.8 on 2026-04-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vocab", "0039_userdailyentitlementusage"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="word_priority",
            field=models.CharField(
                choices=[("new_first", "New first"), ("old_first", "Old first")],
                default="new_first",
                max_length=20,
            ),
        ),
    ]
