# Generated by Django 5.2.16 on 2026-07-15.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vocab", "0043_backgroundjob"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="vocabularyitem",
            index=models.Index(
                fields=["user", "course_code", "-updated_at", "-id"],
                name="vocab_word_list_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vocabularyitem",
            index=models.Index(
                fields=["user", "course_code", "is_learned", "-created_at", "-id"],
                name="vocab_word_new_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vocabularyitem",
            index=models.Index(
                fields=["user", "course_code", "is_learned", "updated_at", "id"],
                name="vocab_word_review_idx",
            ),
        ),
    ]
