# Generated by Django 5.2.16 on 2026-07-15.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("vocab", "0044_vocabularyitem_query_indexes")]

    operations = [
        migrations.CreateModel(
            name="UserStudyDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_code",
                    models.CharField(
                        choices=[("en", "English"), ("ka", "Georgian")],
                        default="en",
                        max_length=10,
                    ),
                ),
                ("study_date", models.DateField()),
                ("correct_answers", models.PositiveIntegerField(default=0)),
                ("streak_qualified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE, to="vocab.telegramuser"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="userstudyday",
            constraint=models.UniqueConstraint(
                fields=("user", "course_code", "study_date"),
                name="unique_user_course_study_day",
            ),
        ),
        migrations.AddIndex(
            model_name="userstudyday",
            index=models.Index(
                fields=["user", "course_code", "-study_date"],
                name="vocab_study_day_idx",
            ),
        ),
    ]
