# Generated by Django 5.2.16 on 2026-07-15.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("vocab", "0045_userstudyday")]

    operations = [
        migrations.AddIndex(
            model_name="apperrorlog",
            index=models.Index(
                fields=["created_at"], name="vocab_error_log_created_idx"
            ),
        )
    ]
