# Generated by Django 5.2.16 on 2026-07-16 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0048_openaiusageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('authenticated', 'Authenticated'), ('words_created', 'Words created'), ('pack_words_added', 'Pack words added'), ('practice_completed', 'Practice completed'), ('paywall_opened', 'Paywall opened'), ('checkout_started', 'Checkout started'), ('subscription_activated', 'Subscription activated')], max_length=64)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vocab.telegramuser')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['name', '-occurred_at'], name='vocab_event_name_time_idx'), models.Index(fields=['user', '-occurred_at'], name='vocab_event_user_time_idx')],
            },
        ),
    ]
