"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.core.exceptions import ImproperlyConfigured

from core.env import env, env_csv, get_secret_key

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_secret_key()

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = env("DEBUG", cast=bool, default=False)

if not DEBUG:
    if SECRET_KEY.startswith("django-insecure-") or len(SECRET_KEY) < 50:
        raise ImproperlyConfigured(
            "Insecure SECRET_KEY detected. Generate a long random key and set it via environment variables."
        )

ALLOWED_HOSTS = [
    "185.250.37.204",
    "localhost",
    "127.0.0.1",
    "vmi2583759.contaboserver.net",
    "vocabume.k1prod.com",
]

CSRF_TRUSTED_ORIGINS = env_csv(
    "CSRF_TRUSTED_ORIGINS", default="https://vocabume.k1prod.com"
)

if not DEBUG:
    SECURE_SSL_REDIRECT = env("SECURE_SSL_REDIRECT", cast=bool, default=True)
    SESSION_COOKIE_SECURE = env("SESSION_COOKIE_SECURE", cast=bool, default=True)
    CSRF_COOKIE_SECURE = env("CSRF_COOKIE_SECURE", cast=bool, default=True)

    SECURE_HSTS_SECONDS = env("SECURE_HSTS_SECONDS", cast=int, default=31536000)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env(
        "SECURE_HSTS_INCLUDE_SUBDOMAINS", cast=bool, default=True
    )
    SECURE_HSTS_PRELOAD = env("SECURE_HSTS_PRELOAD", cast=bool, default=True)

    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "vocab",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "core.security.SecurityHeadersMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "frontend" / "dist"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"

CELERY_BROKER_URL = env("CELERY_BROKER_URL", default="")
CELERY_RESULT_BACKEND = env("CELERY_RESULT_BACKEND", default="")
CELERY_TASK_DEFAULT_QUEUE = "vocabume-high"
CELERY_TASK_ROUTES = {
    "vocab.tasks.process_background_job_high": {"queue": "vocabume-high"},
    "vocab.tasks.process_background_job_low": {"queue": "vocabume-low"},
}
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_TASK_TIME_LIMIT = 300
CELERY_TASK_SOFT_TIME_LIMIT = 270
CELERY_BEAT_SCHEDULE = {
    "send-reminders-every-minute": {
        "task": "vocab.tasks.send_reminders",
        "schedule": 60.0,
        "options": {"queue": "vocabume-low"},
    },
    "clear-stale-image-generation-flags-every-five-minutes": {
        "task": "vocab.tasks.clear_stale_image_generation_flags",
        "schedule": 300.0,
        "options": {"queue": "vocabume-low"},
    },
    "purge-product-analytics-daily": {
        "task": "vocab.tasks.purge_product_analytics",
        "schedule": 86_400.0,
        "options": {"queue": "vocabume-low"},
    },
}

# Bounded request bodies protect JSON endpoints and speech uploads before they
# reach application code.  The web server must enforce the same limit.
DATA_UPLOAD_MAX_MEMORY_SIZE = env(
    "DATA_UPLOAD_MAX_MEMORY_SIZE", cast=int, default=12 * 1024 * 1024
)
FILE_UPLOAD_MAX_MEMORY_SIZE = env(
    "FILE_UPLOAD_MAX_MEMORY_SIZE", cast=int, default=10 * 1024 * 1024
)
MAX_JSON_BODY_BYTES = env("MAX_JSON_BODY_BYTES", cast=int, default=64 * 1024)
TELEGRAM_AUTH_MAX_AGE_SECONDS = env(
    "TELEGRAM_AUTH_MAX_AGE_SECONDS", cast=int, default=300
)

# A shared Redis cache is required in production for rate limits to work across
# web workers.  LocMemCache remains a deliberately explicit local fallback.
CACHES = {
    "default": {
        "BACKEND": env(
            "CACHE_BACKEND", default="django.core.cache.backends.locmem.LocMemCache"
        ),
        "LOCATION": env("CACHE_LOCATION", default="vocabume-local"),
    }
}


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": env("DB_NAME", required=True),
        "USER": env("DB_USER", required=True),
        "PASSWORD": env("DB_PASSWORD", required=True),
        "HOST": env("DB_HOST", required=True),
        "PORT": env("DB_PORT", required=True),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [path for path in [BASE_DIR / "frontend" / "dist"] if path.exists()]

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        }
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
            "stream": "ext://sys.stdout",
        }
    },
    "root": {
        "handlers": ["console"],
        "level": env("LOG_LEVEL", default="INFO"),
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
