from django.urls import path

from . import views


urlpatterns = [
    path("", views.spa_index, name="spa-index"),
    path("api/app-config", views.app_config, name="app-config"),
    path("api/auth/me", views.auth_me, name="auth-me"),
    path("api/auth/logout", views.auth_logout, name="auth-logout"),
    path("api/auth/telegram/request-link", views.auth_request_link, name="auth-request-link"),
    path("api/auth/telegram/poll/<str:token>", views.auth_poll_link, name="auth-poll-link"),
    path("api/auth/telegram/widget", views.auth_telegram_widget, name="auth-telegram-widget"),
    path("api/auth/telegram/webapp", views.auth_telegram_webapp, name="auth-telegram-webapp"),
    path("api/client-error", views.client_error_log, name="client-error-log"),
    path("api/dashboard", views.dashboard, name="dashboard"),
    path("api/words", views.words, name="words"),
    path("api/words/draft", views.word_draft_create, name="word-draft-create"),
    path("api/words/draft/<int:draft_id>/translation", views.word_draft_confirm_translation, name="word-draft-confirm-translation"),
    path("api/words/draft/<int:draft_id>/image/regenerate", views.word_draft_regenerate_image, name="word-draft-regenerate-image"),
    path("api/words/draft/<int:draft_id>/save", views.word_draft_save, name="word-draft-save"),
    path("api/words/draft/<int:draft_id>", views.word_draft_delete, name="word-draft-delete"),
    path("api/words/<int:word_id>", views.word_detail, name="word-detail"),
    path("api/words/<int:word_id>/image/regenerate", views.word_image_regenerate, name="word-image-regenerate"),
    path("api/packs", views.packs_view, name="packs"),
    path("api/packs/prepare", views.packs_prepare, name="packs-prepare"),
    path("api/packs/add", views.packs_add, name="packs-add"),
    path("api/settings", views.settings_view, name="settings"),
    path("api/learn/question", views.learn_question, name="learn-question"),
    path("api/learn/answer", views.learn_answer, name="learn-answer"),
    path("api/study/cards", views.study_cards, name="study-cards"),
    path("api/study/answer", views.study_answer, name="study-answer"),
    path("api/practice/question", views.practice_question, name="practice-question"),
    path("api/practice/answer", views.practice_answer, name="practice-answer"),
    path("api/listening/question", views.listening_question, name="listening-question"),
    path("api/listening/answer", views.listening_answer, name="listening-answer"),
    path("api/speaking/question", views.speaking_question, name="speaking-question"),
    path("api/speaking/answer", views.speaking_answer, name="speaking-answer"),
    path("api/audio/<int:word_id>", views.word_audio, name="word-audio"),
    path("api/image/<int:word_id>", views.word_image, name="word-image"),
    path("api/draft-image/<int:draft_id>", views.draft_image, name="draft-image"),
    path("api/irregular/list", views.irregular_list, name="irregular-list"),
    path("api/irregular/question", views.irregular_question, name="irregular-question"),
    path("api/irregular/answer", views.irregular_answer, name="irregular-answer"),
]
